[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools", 
    "setuptools_scm[toml]",
    "wheel",
]  # PEP 508 specifications.

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.darker]
revision = "a362b28db064c7a4ee38fe66685ba891f33ee5ba"
isort = true

[tool.flakeheaven]
baseline = ".flakeheaven-baseline"
exclude = [
    ".egg",
    ".vscode",
    "build",
    "client",
    "docs",
    "var",
    "venv",
]
max_line_length = 88

[tool.flakeheaven.exceptions."**/__init__.py"]
pyflakes = ["-F401"]

[tool.flakeheaven.exceptions."quipucords/api/migrations/*.py"]
"flake8-*" = [
    "-D100",
    "-D101",
    "-PLC0103", # invalid-name
    "-PLC0114", # missing-module-docstring
    "-PLC0115", # missing-class-docstring
]

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-W503", "-W504", "-W605" ]
pyflakes = ["+*"]
"flake8-*" = ["+*", "-Q000"]
mccabe = ["+*"]

[tool.isort]
profile = "black"
known_first_party = [
    "api",
    "fingerprinter",
    "log_messages",
    "quipucords",
    "scanner",
    "tests",
    "utils",
]

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
init-hook = "import sys; sys.path.append('./quipucords')"
django-settings-module = "quipucords.settings"
load-plugins = [
    "pylint_django",
    "pylint_pytest",
]

[tool.pylint.messages_control]
disable = [
    # flakeheaven lint with --diff parameter seems to be incompatible with this check
    "cannot-enumerate-pytest-fixtures",
    "logging-fstring-interpolation",
    "wrong-import-order",
]

[tool.pytest.ini_options]
pythonpath = "quipucords/"
addopts = [
    "--ds=quipucords.settings",
]
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
    "tests_*.py",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]