---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    # dockerfile: you could add a Dockerfile.j2 here for extra config. It has to be located under ../common/Dockerfile.j2
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
    command: ${MOLECULE_PODMAN_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
